// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: olt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OltDefaultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Manufacturer string `protobuf:"bytes,1,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Hostname     string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port         string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Username     string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password     string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Unm          string `protobuf:"bytes,6,opt,name=unm,proto3" json:"unm,omitempty"`
	Slot         string `protobuf:"bytes,7,opt,name=slot,proto3" json:"slot,omitempty"`
}

func (x *OltDefaultRequest) Reset() {
	*x = OltDefaultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_olt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OltDefaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltDefaultRequest) ProtoMessage() {}

func (x *OltDefaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltDefaultRequest.ProtoReflect.Descriptor instead.
func (*OltDefaultRequest) Descriptor() ([]byte, []int) {
	return file_olt_proto_rawDescGZIP(), []int{0}
}

func (x *OltDefaultRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *OltDefaultRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *OltDefaultRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *OltDefaultRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OltDefaultRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *OltDefaultRequest) GetUnm() string {
	if x != nil {
		return x.Unm
	}
	return ""
}

func (x *OltDefaultRequest) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

type OltSeeSignalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OltDefault *OltDefaultRequest `protobuf:"bytes,1,opt,name=oltDefault,proto3" json:"oltDefault,omitempty"`
	Pon        string             `protobuf:"bytes,2,opt,name=pon,proto3" json:"pon,omitempty"`
	Positions  []string           `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Serials    []string           `protobuf:"bytes,4,rep,name=serials,proto3" json:"serials,omitempty"`
}

func (x *OltSeeSignalRequest) Reset() {
	*x = OltSeeSignalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_olt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OltSeeSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltSeeSignalRequest) ProtoMessage() {}

func (x *OltSeeSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_olt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltSeeSignalRequest.ProtoReflect.Descriptor instead.
func (*OltSeeSignalRequest) Descriptor() ([]byte, []int) {
	return file_olt_proto_rawDescGZIP(), []int{1}
}

func (x *OltSeeSignalRequest) GetOltDefault() *OltDefaultRequest {
	if x != nil {
		return x.OltDefault
	}
	return nil
}

func (x *OltSeeSignalRequest) GetPon() string {
	if x != nil {
		return x.Pon
	}
	return ""
}

func (x *OltSeeSignalRequest) GetPositions() []string {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *OltSeeSignalRequest) GetSerials() []string {
	if x != nil {
		return x.Serials
	}
	return nil
}

type OltSeeSignalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *OltSeeSignalResponse) Reset() {
	*x = OltSeeSignalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_olt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OltSeeSignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OltSeeSignalResponse) ProtoMessage() {}

func (x *OltSeeSignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_olt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OltSeeSignalResponse.ProtoReflect.Descriptor instead.
func (*OltSeeSignalResponse) Descriptor() ([]byte, []int) {
	return file_olt_proto_rawDescGZIP(), []int{2}
}

func (x *OltSeeSignalResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_olt_proto protoreflect.FileDescriptor

var file_olt_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x11, 0x4f, 0x6c, 0x74, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x75, 0x66, 0x61, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x6e, 0x6d, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x6e, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c,
	0x6f, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x6f, 0x74, 0x22, 0x9d,
	0x01, 0x0a, 0x13, 0x4f, 0x6c, 0x74, 0x53, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0a, 0x6f, 0x6c, 0x74, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x6c, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x6f, 0x6c, 0x74, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x2a,
	0x0a, 0x14, 0x4f, 0x6c, 0x74, 0x53, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x5d, 0x0a, 0x0a, 0x4f, 0x6c,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4f, 0x0a, 0x0c, 0x4f, 0x6c, 0x74, 0x53,
	0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x1e, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x6c, 0x74, 0x53, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4f, 0x6c, 0x74, 0x53, 0x65, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_olt_proto_rawDescOnce sync.Once
	file_olt_proto_rawDescData = file_olt_proto_rawDesc
)

func file_olt_proto_rawDescGZIP() []byte {
	file_olt_proto_rawDescOnce.Do(func() {
		file_olt_proto_rawDescData = protoimpl.X.CompressGZIP(file_olt_proto_rawDescData)
	})
	return file_olt_proto_rawDescData
}

var file_olt_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_olt_proto_goTypes = []interface{}{
	(*OltDefaultRequest)(nil),    // 0: equipment.OltDefaultRequest
	(*OltSeeSignalRequest)(nil),  // 1: equipment.OltSeeSignalRequest
	(*OltSeeSignalResponse)(nil), // 2: equipment.OltSeeSignalResponse
}
var file_olt_proto_depIdxs = []int32{
	0, // 0: equipment.OltSeeSignalRequest.oltDefault:type_name -> equipment.OltDefaultRequest
	1, // 1: equipment.OltService.OltSeeSignal:input_type -> equipment.OltSeeSignalRequest
	2, // 2: equipment.OltService.OltSeeSignal:output_type -> equipment.OltSeeSignalResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_olt_proto_init() }
func file_olt_proto_init() {
	if File_olt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_olt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OltDefaultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_olt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OltSeeSignalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_olt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OltSeeSignalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_olt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_olt_proto_goTypes,
		DependencyIndexes: file_olt_proto_depIdxs,
		MessageInfos:      file_olt_proto_msgTypes,
	}.Build()
	File_olt_proto = out.File
	file_olt_proto_rawDesc = nil
	file_olt_proto_goTypes = nil
	file_olt_proto_depIdxs = nil
}
