### Find All
GET {{host}}/configuration/api/company
{{tokenacess}}


### Find By Id
GET {{host}}/configuration/api/company/1
{{tokenacess}}


### Create
POST {{host}}/configuration/api/company
{{tokenacess}}
Content-Type: application/json

{
  "name": "Company",
  "cnpj": "11012728994",
  "vlan": 1212
}


### Update
PUT {{host}}/configuration/api/company/1
{{tokenacess}}
Content-Type: application/json

{
  "name": "Company",
  "cnpj": "11012728994321",
  "vlan": 1212
}
